language: java
dist: bionic
sudo: false

jdk:
  # - oraclejdk8  # deactivated b/c travis does not support this version in any distro > trusty
  - oraclejdk11
  - openjdk8
  - openjdk11

#branches:
#  only:
#    - master
install: mvn install

notifications:
  email:
    recipients:
      - juraj.somorovsky@hackmanit.de
      - robert.merget@rub.de
